### ISSUE TITLE
Consider a byte-coded implementation

### ISSUE THREAD

**Issue by ianwild** [ianwild/qsl#1]
The current (2015-11-04) version interprets directly from the list structure entered by the user.  During the initial planning, I thought this would be the only possible strategy, given the ROM and RAM constraints, and it was _certainly_ the only way to meet the artificial, self-imposed, "within a month" deadline.  However, the initial goal has been reached and, even without turning on the `-Os` option, over 50% of the flash is still available.

Is this enough to fit in a primitive byte-code compiler and interpreter?

**Comment by ianwild** [comment]
Hmmm.  It seems that `Arduino.mk` decided I really wanted to use `-Os` despite my explicitly adding `-O6` to the `CFLAGS`, which is why the code was so small.

**Comment by leyap** [comment]
Hi, how to build to to a hex file?

**Comment by leyap** [comment]
Hi, how to build it to hex file?

**Comment by ianwild** [comment]
Assuming you're on Linux ...

A plain `make` in the source directory will build a Linux executable.  This is useful for syntax checking, and may even run if your processor allows unaligned loads and stores (like the x86 and some flavours of ARM).

Once you're happy with that, a `make arduino` will remove any existing `arduino` sub-directory, create a new one full of hard links to various files in the current directory, and then do a `make` in the new directory.  You'll need to have some variant of `Arduino.mk` installed.  The `include` at the bottom of `arduino.mak` works for the version that comes with Debian, but may need to be modified if yours lives somewhere else.

**Comment by ianwild** [comment]
_(I think it's a bit of a UI design flaw for Github to put the "close issue" and "comment on issue" buttons so close together!)_

**Comment by ianwild** [comment]
Well, only a _very_ long time later, I've finally got a bytecode compiler and interpreter, can still run (a slightly modified version of) my `blink` example, using less RAM than before (a 1024-byte heap, instead of 1280 bytes), and _still_ over 50% of the flash is free.
